name: construculator
description: "A calculator for construction workers"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  
  cupertino_icons: 1.0.8
  flutter_bloc: 9.1.0
  flutter_modular: 6.3.4
  
  supabase_flutter: 2.9.0
  flutter_dotenv: 5.2.1
  logger: 2.5.0
  stack_trace: 1.12.1
  equatable: 2.0.7
  rxdart: 0.28.0
  freezed_annotation: 3.0.0
  json_annotation: 4.9.0
  core_ui:
    git:
      url: https://github.com/ripplearc/coreui.git
      ref: refactor/ui-components
  pinput: 5.0.1
  dartz: 0.10.1



  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 5.0.0
  flutter_launcher_icons: 0.14.3
  flutter_native_splash: 2.4.6
  build_runner: 2.4.15
  mutation_test: 1.7.0
  freezed: 3.0.6
  json_serializable: 6.9.5
  custom_lint: 0.7.5
  ripplearc_flutter_lint: 0.2.2
  bloc_test: 10.0.0


flutter:
  generate: true
  uses-material-design: true
  
  assets:
    # Environment files
    - assets/env/
    - assets/icons/
    - assets/images/

flutter_native_splash:
  image: "assets/icons/splash_icon.png"
  background_image: "assets/images/splash_bg.png"
  android: true
  ios: true
  android_12:
    image: "assets/icons/splash_icon.png"
    color: "#015B7C"
    icon_background_color: "#FFFFFF"